name: Run Python tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test puzzle; 2020 - Day 1
      run: |
        pytest 2020/day_1
    - name: Test puzzle; 2020 - Day 2
      run: |
        pytest 2020/day_2
    - name: Test puzzle; 2020 - Day 3
      run: |
        pytest 2020/day_3
    - name: Test puzzle; 2020 - Day 4
      run: |
        pytest 2020/day_4
    - name: Test puzzle; 2020 - Day 5
      run: |
        pytest 2020/day_5