name: Run Python tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate .coveragerc
      run: |
        echo -e "[report]\n\nexclude_lines =\n\tif __name__ == .__main__.:" >> .coveragerc
        echo "================================================================="
        cat .coveragerc
    - name: Test puzzles of 2020
      run: |
        pytest --cov=./2020 --cov-report=xml 2020/tests
    - name: Upload 2020 coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
        directory: ./coverage/reports/ # optional
        flags: unittests # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)